language: cpp
addons:
  apt:
    packages:
    - libssl-dev
before_script:
- wget https://github.com/libimobiledevice-win32/libplist/releases/download/1.12-gcc/libplist.tar.gz
- wget https://github.com/libimobiledevice-win32/libusbmuxd/releases/download/1.0.10-gcc/libusbmuxd.tar.gz
- mkdir $HOME/ext
- tar -xvzf libplist.tar.gz -C $HOME/ext
- tar -xvzf libusbmuxd.tar.gz -C $HOME/ext
- find $HOME/ext
- sed -i 's/\/home\/travis\/out/\/home\/travis\/ext/g' $HOME/ext/lib/pkgconfig/*.pc
- sed -i 's/\/home\/travis\/out/\/home\/travis\/ext/g' $HOME/ext/lib/*.la
script:
- export CFLAGS=-I$HOME/ext/include
- export PKG_CONFIG_PATH=$HOME/ext/lib/pkgconfig:$PKG_CONFIG_PATH
- export LDFLAGS=-L$HOME/ext/lib
- pkg-config --print-errors --variable=prefix libplist
- pkg-config --print-errors --variable=prefix libusbmuxd
- "./autogen.sh"
- "./configure --prefix=$HOME/out"
- make
after_success:
- make install
- tar -zcvf libimobiledevice.tar.gz -C $HOME/out .
deploy:
  provider: releases
  file: libimobiledevice.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: FmxWArJ3UBoe9/rwvAUCLrhKTctJ3ur7QS0Ho9wGkKHKQByNuB0cI1kruPpu3faTxGgBwVNH92asACGboyfhSejE/qAG8BdLA0z2+2jRJ/q0jglt/kqDcx3DkNq+eMJpGT/btmYiyD8bkKfLbwzpoEpbdrjydCMq3l0i868avk0=
